from HTMLParser import HTMLParser


class MyHTMLParser(HTMLParser):
    def handle_data(self, data):
        print data
        task.description = data
    taskApi.updateTask(task)

data={'System.Reason': 'New', 'Microsoft.VSTS.Common.StateChangeDate': '2020-02-07T23:52:54.373Z', 'System.History': '<div><div style="box-sizing:border-box;margin:0px;color:rgba(0, 0, 0, 0.9);"><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><span style="box-sizing:border-box;">Config:<br style="box-sizing:border-box;"></span><div style="box-sizing:border-box;">config-enterprise-KVMs - #1.0.0.00019<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">Shared flows:<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">sf-enterprise-WsSecUsernameToken-v1 - #1.0.0.00025<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">sf-enterprise-WsSecX509Signature-v1 - #1.0.0.00002<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">sf-enterprise-ZeusHashToken-v1 &nbsp; &nbsp; &nbsp;- #1.0.0.00003<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">sf-enterprise-GenericSOAPSecFlow-v1 - #1.0.0.00002<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;"><br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">Proxies:<br style="box-sizing:border-box;"></div><div style="box-sizing:border-box;">soap-SOAEndpointEntry-v1 &nbsp; - #1.0.0.00001<br style="box-sizing:border-box;"></div><span style="box-sizing:border-box;">soap-DepositAccount-getCostCenter-v1_1 - #1.0.0.00001</span><br style="box-sizing:border-box;"></span></div></div><div style="box-sizing:border-box;margin:0px;color:rgba(0, 0, 0, 0.9);"><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><span style="box-sizing:border-box;"><br style="box-sizing:border-box;"></span></span></div></div><div style="box-sizing:border-box;margin:0px;color:rgba(0, 0, 0, 0.9);"><div style="box-sizing:border-box;"><span style="box-sizing:border-box;"><span style="box-sizing:border-box;">has been created.</span></span></div></div><br></div>', 'System.WorkItemType': 'User Story', 'System.CommentCount': '1', 'WEF_F96A6E557E69456090472041E626AD44_Kanban.Column.Done': 'false', 'WEF_F96A6E557E69456090472041E626AD44_Kanban.Column': 'New', 'Microsoft.VSTS.Common.ValueArea': 'Business', 'System.CreatedBy': 'Suwantha Appuhamy <suwantha.appuhamy@zionsbancorp.com>', 'System.ChangedDate': '2020-02-07T23:52:54.373Z', 'System.Description': '<div>this is test</div>', 'System.Title': 'test ', 'System.ChangedBy': 'Suwantha Appuhamy <suwantha.appuhamy@zionsbancorp.com>', 'System.AssignedTo': 'Suwantha Appuhamy <suwantha.appuhamy@zionsbancorp.com>', 'System.TeamProject': 'IFAPI', 'System.BoardColumn': 'New', 'System.IterationPath': 'IFAPI\Sprint 19', 'Microsoft.VSTS.Common.Priority': '2', 'System.AreaPath': 'IFAPI', 'System.BoardColumnDone': 'false', 'System.State': 'New', 'Custom.SubState': 'New', 'System.CreatedDate': '2020-02-07T23:52:54.373Z'}
#print data['System.History']
parser = MyHTMLParser()
parser.feed(data['System.History'])
parser.description = data
